[project]
name = "universal-ffmpeg-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller>=6.17.0",
    "pyqt6>=6.10.1",
]
